package lintrules

// GolangCILintRules is the curated allow-list of `golangci-lint` linter names
// recognised by dreamer. Linters not present here are dropped in strict mode
// and tagged `[unverified]` in permissive mode.
var GolangCILintRules = stringSet(
	// staticcheck family
	"staticcheck",
	"stylecheck",
	"gosimple",
	"unused",

	// core toolchain
	"govet",
	"errcheck",
	"ineffassign",
	"typecheck",

	// commonly enabled defaults
	"asciicheck",
	"bidichk",
	"bodyclose",
	"contextcheck",
	"copyloopvar",
	"cyclop",
	"decorder",
	"depguard",
	"dogsled",
	"dupl",
	"dupword",
	"durationcheck",
	"errchkjson",
	"errname",
	"errorlint",
	"exhaustive",
	"exhaustruct",
	"exptostd",
	"fatcontext",
	"forbidigo",
	"forcetypeassert",
	"funcorder",
	"funlen",
	"gci",
	"ginkgolinter",
	"gocheckcompilerdirectives",
	"gochecknoglobals",
	"gochecknoinits",
	"gocognit",
	"goconst",
	"gocritic",
	"gocyclo",
	"godot",
	"godox",
	"gofmt",
	"gofumpt",
	"goheader",
	"goimports",
	"gomoddirectives",
	"gomodguard",
	"goprintffuncname",
	"gosec",
	"gosmopolitan",
	"grouper",
	"importas",
	"inamedparam",
	"interfacebloat",
	"intrange",
	"ireturn",
	"lll",
	"loggercheck",
	"maintidx",
	"makezero",
	"mirror",
	"misspell",
	"mnd",
	"musttag",
	"nakedret",
	"nestif",
	"nilerr",
	"nilness",
	"nilnil",
	"nlreturn",
	"noctx",
	"nolintlint",
	"nonamedreturns",
	"nosprintfhostport",
	"paralleltest",
	"perfsprint",
	"prealloc",
	"predeclared",
	"promlinter",
	"protogetter",
	"reassign",
	"recvcheck",
	"revive",
	"rowserrcheck",
	"sloglint",
	"sqlclosecheck",
	"tagalign",
	"tagliatelle",
	"testableexamples",
	"testifylint",
	"testpackage",
	"thelper",
	"tparallel",
	"unconvert",
	"unparam",
	"usestdlibvars",
	"usetesting",
	"varnamelen",
	"wastedassign",
	"whitespace",
	"wrapcheck",
	"wsl",
	"zerologlint",
)
