package readers

import (
	"regexp"
	"strings"
)

const (
	// ≈ 1k tokens × 250 msgs ≈ context budget for one analysis prompt.
	claudeMaxCharsPerMessage   = 4000
	claudeMaxMessagesPerSource = 250
)

var (
	claudeANSIEscapePattern    = regexp.MustCompile(`\x1b\[[0-9;?]*[ -/]*[@-~]`)
	claudeWrapperTagPattern    = regexp.MustCompile(`(?s)</?[^>]+>`)
	claudeWhitespaceBurstRegex = regexp.MustCompile(`[\t\r\n ]+`)
)

type claudeDropRule struct {
	name               string
	rawTokens          []string
	normalizedTokens   []string
	normalizedPrefixes []string
}

var claudeDropRules = []claudeDropRule{
	{
		name:               "meta-sidechain-compact-summary",
		rawTokens:          []string{"<meta", "<sidechain", "<compact-summary"},
		normalizedPrefixes: []string{"meta:", "sidechain:", "compact-summary:"},
	},
	{
		name:             "local-command-wrappers",
		rawTokens:        []string{"<local-command-", "<command-name>", "<command-message>", "<command-args>"},
		normalizedTokens: []string{"generated by the user while running local commands"},
	},
	{
		name:      "task-lifecycle-notifications",
		rawTokens: []string{"<task-notification", "<task-id>", "<tool-use-id>", "<output-file>", "<status>", "<summary>", "<result>", "<usage>"},
	},
	{
		name:             "tool-chatter",
		normalizedTokens: []string{"tool_use", "tool_result", "attachments:", "output_file:", "agentid:", "internal id - do not mention to user", "do not read or tail this file via the shell tool", "manifest:", "async agent launched successfully", "the agent is working in the background", "you will be notified automatically when it completes", "do not duplicate this agent's work"},
	},
}

func SanitizeClaudeMessages(messages []ChatMessage) []ChatMessage {
	if len(messages) == 0 {
		return nil
	}

	sanitized := make([]ChatMessage, 0, min(len(messages), claudeMaxMessagesPerSource))
	previousKey := ""

	for _, message := range messages {
		normalizedContent := normalizeClaudeContent(message.Content)
		if normalizedContent == "" {
			continue
		}

		rawLower := strings.ToLower(message.Content)
		normalizedLower := strings.ToLower(normalizedContent)
		if shouldDropClaudeMessage(rawLower, normalizedLower) {
			continue
		}

		dedupeKey := message.Role + "\x00" + normalizedContent
		if dedupeKey == previousKey {
			continue
		}

		message.Content = normalizedContent
		sanitized = append(sanitized, message)
		previousKey = dedupeKey

		if claudeMaxMessagesPerSource > 0 && len(sanitized) >= claudeMaxMessagesPerSource {
			break
		}
	}

	return sanitized
}

func normalizeClaudeContent(content string) string {
	normalized := claudeANSIEscapePattern.ReplaceAllString(content, "")
	normalized = claudeWrapperTagPattern.ReplaceAllString(normalized, " ")
	normalized = claudeWhitespaceBurstRegex.ReplaceAllString(normalized, " ")
	normalized = strings.TrimSpace(normalized)
	if normalized == "" {
		return ""
	}

	runes := []rune(normalized)
	if len(runes) > claudeMaxCharsPerMessage {
		normalized = strings.TrimSpace(string(runes[:claudeMaxCharsPerMessage]))
	}

	return normalized
}

func shouldDropClaudeMessage(rawLower string, normalizedLower string) bool {
	for _, rule := range claudeDropRules {
		if containsAny(rawLower, rule.rawTokens...) {
			return true
		}
		if containsAny(normalizedLower, rule.normalizedTokens...) {
			return true
		}
		if containsAnyPrefix(normalizedLower, rule.normalizedPrefixes...) {
			return true
		}
	}
	return false
}

func containsAnyPrefix(content string, prefixes ...string) bool {
	for _, prefix := range prefixes {
		if strings.HasPrefix(content, prefix) {
			return true
		}
	}
	return false
}

func containsAny(content string, tokens ...string) bool {
	for _, token := range tokens {
		if strings.Contains(content, token) {
			return true
		}
	}
	return false
}
