package readers

import (
	"regexp"
	"strings"
)

const (
	// ≈ 1k tokens × 250 msgs ≈ context budget for one analysis prompt.
	claudeMaxCharsPerMessage   = 4000
	claudeMaxMessagesPerSource = 250
)

var claudeWrapperTagPattern = regexp.MustCompile(`(?s)</?[^>]+>`)

type claudeDropRule struct {
	name               string
	rawTokens          []string
	normalizedTokens   []string
	normalizedPrefixes []string
}

var claudeDropRules = []claudeDropRule{
	{
		name:               "meta-sidechain-compact-summary",
		rawTokens:          []string{"<meta", "<sidechain", "<compact-summary"},
		normalizedPrefixes: []string{"meta:", "sidechain:", "compact-summary:"},
	},
	{
		name:             "local-command-wrappers",
		rawTokens:        []string{"<local-command-", "<command-name>", "<command-message>", "<command-args>"},
		normalizedTokens: []string{"generated by the user while running local commands"},
	},
	{
		name:      "task-lifecycle-notifications",
		rawTokens: []string{"<task-notification", "<task-id>", "<tool-use-id>", "<output-file>", "<status>", "<summary>", "<result>", "<usage>"},
	},
	{
		name:             "tool-chatter",
		normalizedTokens: []string{"attachments:", "output_file:", "agentid:", "internal id - do not mention to user", "do not read or tail this file via the shell tool", "manifest:", "async agent launched successfully", "the agent is working in the background", "you will be notified automatically when it completes", "do not duplicate this agent's work"},
	},
}

func SanitizeClaudeMessages(messages []ChatMessage) []ChatMessage {
	return sanitizeMessages(messages, normalizeClaudeContent, shouldDropClaudeMessage, claudeMaxMessagesPerSource)
}

func normalizeClaudeContent(content string) string {
	normalized := ANSIEscapePattern.ReplaceAllString(content, "")
	normalized = claudeWrapperTagPattern.ReplaceAllString(normalized, " ")
	normalized = WhitespaceBurstRegex.ReplaceAllString(normalized, " ")
	normalized = strings.TrimSpace(normalized)
	if normalized == "" {
		return ""
	}

	// Truncate to claudeMaxCharsPerMessage runes without allocating a []rune
	// slice. Ranging over a string yields rune boundaries at zero cost.
	runeCount := 0
	for i := range normalized {
		if runeCount == claudeMaxCharsPerMessage {
			normalized = strings.TrimSpace(normalized[:i])
			break
		}
		runeCount++
	}

	return normalized
}

func shouldDropClaudeMessage(rawLower string, normalizedLower string) bool {
	for _, rule := range claudeDropRules {
		if containsAny(rawLower, rule.rawTokens...) {
			return true
		}
		if containsAny(normalizedLower, rule.normalizedTokens...) {
			return true
		}
		if containsAnyPrefix(normalizedLower, rule.normalizedPrefixes...) {
			return true
		}
	}
	return false
}

func containsAnyPrefix(content string, prefixes ...string) bool {
	for _, prefix := range prefixes {
		if strings.HasPrefix(content, prefix) {
			return true
		}
	}
	return false
}

func containsAny(content string, tokens ...string) bool {
	for _, token := range tokens {
		if strings.Contains(content, token) {
			return true
		}
	}
	return false
}
