package readers

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func TestReadJSONLParsesMessagesAndSkipsMalformedLines(t *testing.T) {
	filePath := filepath.Join(t.TempDir(), "session.jsonl")
	contents := strings.Join([]string{
		`{"role":"user","content":"hello","timestamp":"2024-01-01T00:00:00Z"}`,
		`{this is not valid json}`,
		`{"message":{"author":{"role":"assistant"},"content":{"parts":["hi there"]},"createdAt":1704067800}}`,
		`{"event":"heartbeat"}`,
	}, "\n")

	if err := os.WriteFile(filePath, []byte(contents), 0o644); err != nil {
		t.Fatalf("WriteFile returned error: %v", err)
	}

	messages, err := ReadJSONL(filePath)
	if err != nil {
		t.Fatalf("ReadJSONL returned error: %v", err)
	}
	if len(messages) != 2 {
		t.Fatalf("expected 2 parsed messages, got %d", len(messages))
	}

	if got := messages[0].Role; got != "user" {
		t.Fatalf("first message role = %q, want user", got)
	}
	if got := messages[0].Content; got != "hello" {
		t.Fatalf("first message content = %q, want hello", got)
	}

	expectedSecondTime := time.Unix(1704067800, 0).UTC()
	if got := messages[1].Role; got != "assistant" {
		t.Fatalf("second message role = %q, want assistant", got)
	}
	if got := messages[1].Content; got != "hi there" {
		t.Fatalf("second message content = %q, want hi there", got)
	}
	if !messages[1].Timestamp.Equal(expectedSecondTime) {
		t.Fatalf("second message timestamp = %s, want %s", messages[1].Timestamp, expectedSecondTime)
	}
}

func TestReadJSONLSupportsLargeLines(t *testing.T) {
	filePath := filepath.Join(t.TempDir(), "large-session.jsonl")
	largeContent := strings.Repeat("a", 70*1024)
	line := fmt.Sprintf(`{"role":"user","content":%q}`, largeContent)

	if err := os.WriteFile(filePath, []byte(line+"\n"), 0o644); err != nil {
		t.Fatalf("WriteFile returned error: %v", err)
	}

	messages, err := ReadJSONL(filePath)
	if err != nil {
		t.Fatalf("ReadJSONL returned error: %v", err)
	}
	if len(messages) != 1 {
		t.Fatalf("expected 1 parsed message, got %d", len(messages))
	}
	if got := len(messages[0].Content); got != len(largeContent) {
		t.Fatalf("parsed content length = %d, want %d", got, len(largeContent))
	}
}

func TestReadJSONLReturnsOpenError(t *testing.T) {
	_, err := ReadJSONL(filepath.Join(t.TempDir(), "missing.jsonl"))
	if err == nil {
		t.Fatalf("ReadJSONL expected error for missing file")
	}
}

func TestReadJSONLParsesClaudeCodeSessionRecords(t *testing.T) {
	filePath := filepath.Join(t.TempDir(), "claude-session.jsonl")
	contents := strings.Join([]string{
		`{"type":"queue-operation","sessionId":"abc","operation":"enqueue","timestamp":"2026-05-08T12:00:00Z"}`,
		`{"type":"user","message":{"role":"user","content":"Help me debug this"},"timestamp":"2026-05-08T12:00:01Z"}`,
		`{"type":"assistant","message":{"role":"assistant","content":[{"type":"text","text":"Sure, share the error."}]},"timestamp":"2026-05-08T12:00:02Z"}`,
	}, "\n")

	if err := os.WriteFile(filePath, []byte(contents), 0o644); err != nil {
		t.Fatalf("WriteFile returned error: %v", err)
	}

	messages, err := ReadJSONL(filePath)
	if err != nil {
		t.Fatalf("ReadJSONL returned error: %v", err)
	}
	if len(messages) != 2 {
		t.Fatalf("expected 2 parsed messages, got %d", len(messages))
	}

	if got := messages[0].Role; got != "user" {
		t.Fatalf("first message role = %q, want user", got)
	}
	if got := messages[0].Content; got != "Help me debug this" {
		t.Fatalf("first message content = %q, want expected Claude user content", got)
	}
	if got := messages[1].Role; got != "assistant" {
		t.Fatalf("second message role = %q, want assistant", got)
	}
	if got := messages[1].Content; got != "Sure, share the error." {
		t.Fatalf("second message content = %q, want expected Claude assistant content", got)
	}
}

func TestReadJSONLWithOptionsSanitizesClaudeRecords(t *testing.T) {
	filePath := filepath.Join(t.TempDir(), "claude-session-sanitized.jsonl")
	contents := strings.Join([]string{
		`{"type":"user","message":{"role":"user","content":"<local-command-caveat>generated by the user while running local commands</local-command-caveat>"},"timestamp":"2026-05-08T12:00:00Z"}`,
		`{"type":"user","message":{"role":"user","content":"Need help\nwith tests"},"timestamp":"2026-05-08T12:00:01Z"}`,
		`{"type":"user","message":{"role":"user","content":"Need   help with tests"},"timestamp":"2026-05-08T12:00:02Z"}`,
		`{"type":"user","message":{"role":"user","content":"Async agent launched successfully. agentId: a1 output_file: C:\\temp\\x"},"timestamp":"2026-05-08T12:00:03Z"}`,
		`{"type":"assistant","message":{"role":"assistant","content":"Sure, share go test output."},"timestamp":"2026-05-08T12:00:04Z"}`,
	}, "\n")

	if err := os.WriteFile(filePath, []byte(contents), 0o644); err != nil {
		t.Fatalf("WriteFile returned error: %v", err)
	}

	messages, err := ReadJSONLWithOptions(filePath, JSONLReadOptions{Sanitizer: SanitizeClaudeMessages})
	if err != nil {
		t.Fatalf("ReadJSONLWithOptions returned error: %v", err)
	}
	if len(messages) != 2 {
		t.Fatalf("expected 2 sanitized Claude messages, got %d", len(messages))
	}
	if got := messages[0].Content; got != "Need help with tests" {
		t.Fatalf("first message content = %q, want sanitized content", got)
	}
	if got := messages[1].Content; got != "Sure, share go test output." {
		t.Fatalf("second message content = %q, want assistant content", got)
	}
}

func TestReadJSONLWithOptionsDefaultDoesNotSanitize(t *testing.T) {
	filePath := filepath.Join(t.TempDir(), "claude-session-raw.jsonl")
	contents := strings.Join([]string{
		`{"type":"user","message":{"role":"user","content":"<local-command-stdout>Set model</local-command-stdout>"},"timestamp":"2026-05-08T12:00:00Z"}`,
		`{"type":"user","message":{"role":"user","content":"Need help\nwith tests"},"timestamp":"2026-05-08T12:00:01Z"}`,
		`{"type":"user","message":{"role":"user","content":"Need   help with tests"},"timestamp":"2026-05-08T12:00:02Z"}`,
		`{"type":"assistant","message":{"role":"assistant","content":"Sure, share go test output."},"timestamp":"2026-05-08T12:00:03Z"}`,
	}, "\n")

	if err := os.WriteFile(filePath, []byte(contents), 0o644); err != nil {
		t.Fatalf("WriteFile returned error: %v", err)
	}

	messages, err := ReadJSONLWithOptions(filePath, JSONLReadOptions{})
	if err != nil {
		t.Fatalf("ReadJSONLWithOptions returned error: %v", err)
	}
	if len(messages) != 4 {
		t.Fatalf("expected 4 unsanitized Claude messages, got %d", len(messages))
	}
	if got := messages[0].Content; !strings.Contains(got, "<local-command-stdout>") {
		t.Fatalf("first message content = %q, want unsanitized wrapper content", got)
	}
}

func TestReadJSONLWithOptionsSanitizesNoisyClaudePayloadAndKeepsSignal(t *testing.T) {
	filePath := filepath.Join(t.TempDir(), "claude-noisy-session.jsonl")
	contents := strings.Join([]string{
		`{"type":"user","message":{"role":"user","content":"<meta>trace metadata</meta>"},"timestamp":"2026-05-08T12:00:00Z"}`,
		`{"type":"assistant","message":{"role":"assistant","content":"tool_result: {\"ok\":true}"},"timestamp":"2026-05-08T12:00:01Z"}`,
		`{"type":"user","message":{"role":"user","content":"Async agent launched successfully. agentId: a1 output_file: C:\\temp\\a"},"timestamp":"2026-05-08T12:00:02Z"}`,
		`{"type":"user","message":{"role":"user","content":"  Please investigate flaky daemon cycle behavior.  "},"timestamp":"2026-05-08T12:00:03Z"}`,
		`{"type":"assistant","message":{"role":"assistant","content":[{"type":"text","text":"I will inspect runtime and discovery isolation tests."}]},"timestamp":"2026-05-08T12:00:04Z"}`,
		`{"type":"user","message":{"role":"user","content":"Need help\nwith project A/B isolation"},"timestamp":"2026-05-08T12:00:05Z"}`,
	}, "\n")

	if err := os.WriteFile(filePath, []byte(contents), 0o644); err != nil {
		t.Fatalf("WriteFile returned error: %v", err)
	}

	messages, err := ReadJSONLWithOptions(filePath, JSONLReadOptions{Sanitizer: SanitizeClaudeMessages})
	if err != nil {
		t.Fatalf("ReadJSONLWithOptions returned error: %v", err)
	}
	if len(messages) != 4 {
		t.Fatalf("expected 4 sanitized Claude signal messages, got %d", len(messages))
	}

	if got := messages[0].Content; got != "tool_result: {\"ok\":true}" {
		t.Fatalf("first message content = %q, want kept tool result reference", got)
	}
	if got := messages[1].Content; got != "Please investigate flaky daemon cycle behavior." {
		t.Fatalf("second message content = %q, want kept user signal", got)
	}
	if got := messages[2].Content; got != "I will inspect runtime and discovery isolation tests." {
		t.Fatalf("third message content = %q, want kept assistant signal", got)
	}
	if got := messages[3].Content; got != "Need help with project A/B isolation" {
		t.Fatalf("fourth message content = %q, want normalized user signal", got)
	}

	joined := strings.ToLower(messages[0].Content + " " + messages[1].Content + " " + messages[2].Content + " " + messages[3].Content)
	for _, unwanted := range []string{"<meta>", "async agent launched successfully", "output_file:"} {
		if strings.Contains(joined, unwanted) {
			t.Fatalf("sanitized messages should not include %q: %q", unwanted, joined)
		}
	}
}

func TestReadJSONLParsesCodexResponseItemPayloadMessages(t *testing.T) {
	filePath := filepath.Join(t.TempDir(), "codex-session.jsonl")
	contents := strings.Join([]string{
		`{"type":"session_meta","payload":{"cwd":"C:\\repo"}}`,
		`{"type":"response_item","payload":{"role":"user","content":"Please inspect daemon isolation."},"timestamp":"2026-05-08T12:00:01Z"}`,
		`{"type":"response_item","payload":{"role":"assistant","content":[{"type":"output_text","text":"I found a state merge issue."}]},"timestamp":"2026-05-08T12:00:02Z"}`,
	}, "\n")

	if err := os.WriteFile(filePath, []byte(contents), 0o644); err != nil {
		t.Fatalf("WriteFile returned error: %v", err)
	}

	messages, err := ReadJSONL(filePath)
	if err != nil {
		t.Fatalf("ReadJSONL returned error: %v", err)
	}
	if len(messages) != 2 {
		t.Fatalf("expected 2 parsed Codex messages, got %d", len(messages))
	}

	if got := messages[0].Role; got != "user" {
		t.Fatalf("first message role = %q, want user", got)
	}
	if got := messages[0].Content; got != "Please inspect daemon isolation." {
		t.Fatalf("first message content = %q, want Codex user content", got)
	}
	if got := messages[1].Role; got != "assistant" {
		t.Fatalf("second message role = %q, want assistant", got)
	}
	if got := messages[1].Content; got != "I found a state merge issue." {
		t.Fatalf("second message content = %q, want Codex assistant content", got)
	}
}

func TestReadJSONLParsesCopilotSessionMessagesFromTypedEvents(t *testing.T) {
	filePath := filepath.Join(t.TempDir(), "copilot-session.jsonl")
	contents := strings.Join([]string{
		`{"type":"session.start","data":{"id":"s1"}}`,
		`{"type":"user.message","data":{"content":"How should I fix the daemon?"},"timestamp":"2026-05-08T12:00:01Z"}`,
		`{"type":"assistant.message","data":{"content":"Start by checking runtime routing."},"timestamp":"2026-05-08T12:00:02Z"}`,
		`{"type":"tool.execution_result","data":{"content":"large tool output"}}`,
	}, "\n")

	if err := os.WriteFile(filePath, []byte(contents), 0o644); err != nil {
		t.Fatalf("WriteFile returned error: %v", err)
	}

	messages, err := ReadJSONL(filePath)
	if err != nil {
		t.Fatalf("ReadJSONL returned error: %v", err)
	}
	if len(messages) != 2 {
		t.Fatalf("expected 2 parsed Copilot messages, got %d", len(messages))
	}
	if got := messages[0].Role; got != "user" {
		t.Fatalf("first message role = %q, want user", got)
	}
	if got := messages[0].Content; got != "How should I fix the daemon?" {
		t.Fatalf("first message content = %q, want user content", got)
	}
	if got := messages[1].Role; got != "assistant" {
		t.Fatalf("second message role = %q, want assistant", got)
	}
	if got := messages[1].Content; got != "Start by checking runtime routing." {
		t.Fatalf("second message content = %q, want assistant content", got)
	}
}

func TestReadJSONLWithOptionsSanitizesCopilotSessionNoise(t *testing.T) {
	filePath := filepath.Join(t.TempDir(), "copilot-session-sanitized.jsonl")
	contents := strings.Join([]string{
		`{"type":"session.info","data":{"content":"metadata"}}`,
		`{"type":"assistant.message","data":{"toolRequests":[{"id":"tool-1"}]}}`,
		`{"type":"user.message","data":{"content":"Need help\nwith VS Code chat parsing."}}`,
		`{"type":"user.message","data":{"content":"Need   help with VS Code chat parsing."}}`,
		`{"type":"assistant.message","data":{"content":"Read requests and response markdown only."}}`,
		`{"type":"tool.execution_start","data":{"content":"run command"}}`,
	}, "\n")

	if err := os.WriteFile(filePath, []byte(contents), 0o644); err != nil {
		t.Fatalf("WriteFile returned error: %v", err)
	}

	messages, err := ReadJSONLWithOptions(filePath, JSONLReadOptions{Sanitizer: SanitizeCopilotSessionMessages})
	if err != nil {
		t.Fatalf("ReadJSONLWithOptions returned error: %v", err)
	}
	if len(messages) != 2 {
		t.Fatalf("expected 2 sanitized Copilot messages, got %d", len(messages))
	}
	if got := messages[0].Content; got != "Need help with VS Code chat parsing." {
		t.Fatalf("first message content = %q, want normalized user message", got)
	}
	if got := messages[1].Content; got != "Read requests and response markdown only." {
		t.Fatalf("second message content = %q, want assistant response", got)
	}
}

func TestReadJSONLIgnoresCodexResponseItemsWithoutUserAssistantRole(t *testing.T) {
	filePath := filepath.Join(t.TempDir(), "codex-session-ignore-non-chat.jsonl")
	contents := strings.Join([]string{
		`{"type":"response_item","payload":{"role":"system","content":"internal state checkpoint"}}`,
		`{"type":"response_item","payload":{"role":"tool","content":"tool output"}}`,
		`{"type":"response_item","payload":{"role":"user","content":"Need help with retries"}}`,
		`{"type":"response_item","payload":{"role":"assistant","content":"Add bounded backoff and tests."}}`,
	}, "\n")

	if err := os.WriteFile(filePath, []byte(contents), 0o644); err != nil {
		t.Fatalf("WriteFile returned error: %v", err)
	}

	messages, err := ReadJSONL(filePath)
	if err != nil {
		t.Fatalf("ReadJSONL returned error: %v", err)
	}
	if len(messages) != 2 {
		t.Fatalf("expected 2 parsed chat messages, got %d", len(messages))
	}

	if got := messages[0].Role; got != "user" {
		t.Fatalf("first message role = %q, want user", got)
	}
	if got := messages[1].Role; got != "assistant" {
		t.Fatalf("second message role = %q, want assistant", got)
	}
}

func TestReadJSONLWithOptionsSanitizesCodexBootstrapMessages(t *testing.T) {
	filePath := filepath.Join(t.TempDir(), "codex-session-sanitized.jsonl")
	contents := strings.Join([]string{
		`{"type":"session_meta","payload":{"cwd":"C:\\repo"}}`,
		`{"type":"response_item","payload":{"type":"message","role":"user","content":[{"type":"input_text","text":"# AGENTS.md instructions for C:\\repo\n\n<INSTRUCTIONS>\nPrioritize readability over cleverness.\n</INSTRUCTIONS>"}]},"timestamp":"2026-05-08T12:00:00Z"}`,
		`{"type":"response_item","payload":{"type":"message","role":"user","content":{"type":"input_text","text":"Please inspect flaky evaluation scoring."}},"timestamp":"2026-05-08T12:00:01Z"}`,
		`{"type":"response_item","payload":{"type":"message","role":"assistant","content":{"type":"output_text","text":"I found the scoring path and will keep the patch narrow."}},"timestamp":"2026-05-08T12:00:02Z"}`,
		`{"type":"response_item","payload":{"type":"message","role":"assistant","content":{"type":"output_text","text":"I found the scoring path and will keep the patch narrow."}},"timestamp":"2026-05-08T12:00:03Z"}`,
	}, "\n")

	if err := os.WriteFile(filePath, []byte(contents), 0o644); err != nil {
		t.Fatalf("WriteFile returned error: %v", err)
	}

	messages, err := ReadJSONLWithOptions(filePath, JSONLReadOptions{Sanitizer: SanitizeCodexMessages})
	if err != nil {
		t.Fatalf("ReadJSONLWithOptions returned error: %v", err)
	}
	if len(messages) != 2 {
		t.Fatalf("expected 2 sanitized Codex messages, got %d", len(messages))
	}
	if got := messages[0].Content; got != "Please inspect flaky evaluation scoring." {
		t.Fatalf("first message content = %q, want user request", got)
	}
	if got := messages[1].Content; got != "I found the scoring path and will keep the patch narrow." {
		t.Fatalf("second message content = %q, want assistant message", got)
	}
}

// ---------------------------------------------------------------------------
// parseTimestamp
// ---------------------------------------------------------------------------

func TestParseTimestamp(t *testing.T) {
	tests := []struct {
		name   string
		value  any
		wantOK bool
		wantTS string // empty means check !ok
	}{
		{"time.Time input", time.Date(2024, 1, 1, 12, 0, 0, 0, time.UTC), true, "2024-01-01T12:00:00Z"},
		{"time.Time non-UTC converted", time.Date(2024, 1, 1, 12, 0, 0, 0, time.FixedZone("EST", -5*3600)), true, "2024-01-01T17:00:00Z"},
		{"RFC3339 string", "2024-06-15T10:30:00Z", true, "2024-06-15T10:30:00Z"},
		{"RFC3339Nano string", "2024-06-15T10:30:00.123456789Z", true, "2024-06-15T10:30:00.123456789Z"},
		{"space-separated layout", "2024-06-15 10:30:00", true, "2024-06-15T10:30:00Z"},
		{"T-separated no-zone layout", "2024-06-15T10:30:00", true, "2024-06-15T10:30:00Z"},
		{"unix seconds string", "1704067200", true, "2024-01-01T00:00:00Z"},
		{"unix milliseconds string", "1704067200000", true, "2024-01-01T00:00:00Z"},
		{"unix microseconds string", "1704067200000000", true, "2024-01-01T00:00:00Z"},
		{"unix nanoseconds string", "1704067200000000000", true, "2024-01-01T00:00:00Z"},
		{"float string", "1704067200.5", true, "2024-01-01T00:00:00Z"},
		{"empty string", "", false, ""},
		{"whitespace string", "   ", false, ""},
		{"non-numeric non-date string", "hello", false, ""},
		{"float64 value", float64(1704067200), true, "2024-01-01T00:00:00Z"},
		{"int64 value", int64(1704067200), true, "2024-01-01T00:00:00Z"},
		{"int value", int(1704067200), true, "2024-01-01T00:00:00Z"},
		{"uint64 value", uint64(1704067200), true, "2024-01-01T00:00:00Z"},
		{"uint64 overflow", uint64(1<<63 + 1), false, ""},
		{"[]byte value", []byte("1704067200"), true, "2024-01-01T00:00:00Z"},
		{"nil value", nil, false, ""},
		{"bool value", false, false, ""},
		{"json.Number int64", json.Number("1704067200"), true, "2024-01-01T00:00:00Z"},
		{"json.Number float64", json.Number("1704067200.5"), true, "2024-01-01T00:00:00Z"},
		{"json.Number nanoseconds", json.Number("1704067200000000000"), true, "2024-01-01T00:00:00Z"},
		{"json.Number unparseable", json.Number("not-a-number"), false, ""},
		{"negative unix seconds", -100, true, "1969-12-31T23:58:20Z"},
		{"zero int64", int64(0), true, "1970-01-01T00:00:00Z"},
		{"zero int", int(0), true, "1970-01-01T00:00:00Z"},
		{"zero float64", float64(0), true, "1970-01-01T00:00:00Z"},
		{"uint64 zero", uint64(0), true, "1970-01-01T00:00:00Z"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, ok := parseTimestamp(tt.value)
			if ok != tt.wantOK {
				t.Fatalf("parseTimestamp(%v) ok = %v, want %v", tt.value, ok, tt.wantOK)
			}
			if tt.wantOK && tt.wantTS != "" {
				parsed, _ := time.Parse(time.RFC3339Nano, tt.wantTS)
				if !got.Equal(parsed) {
					t.Errorf("parseTimestamp(%v) = %v, want %v", tt.value, got, parsed)
				}
			}
		})
	}
}

// ---------------------------------------------------------------------------
// normalizeRole
// ---------------------------------------------------------------------------

func TestNormalizeRole(t *testing.T) {
	tests := []struct {
		input string
		want  string
	}{
		{"user", "user"},
		{"human", "user"},
		{"prompt", "user"},
		{"USER", "user"},
		{" Human ", "user"},
		{"assistant", "assistant"},
		{"model", "assistant"},
		{"ai", "assistant"},
		{"copilot", "assistant"},
		{"bot", "assistant"},
		{"ASSISTANT", "assistant"},
		{" Copilot ", "assistant"},
		{"system", ""},
		{"tool", ""},
		{"foobar", ""},
		{"", ""},
		{"   ", ""},
	}
	for _, tt := range tests {
		t.Run(fmt.Sprintf("input=%q", tt.input), func(t *testing.T) {
			got := normalizeRole(tt.input)
			if got != tt.want {
				t.Errorf("normalizeRole(%q) = %q, want %q", tt.input, got, tt.want)
			}
		})
	}
}

// ---------------------------------------------------------------------------
// parseContentArray
// ---------------------------------------------------------------------------

func TestParseContentArray(t *testing.T) {
	t.Run("nil returns nil", func(t *testing.T) {
		if got := parseContentArray(nil); got != nil {
			t.Errorf("expected nil, got %v", got)
		}
	})

	t.Run("empty array returns nil", func(t *testing.T) {
		if got := parseContentArray([]any{}); got != nil {
			t.Errorf("expected nil for empty array, got %v", got)
		}
	})

	t.Run("string type returns nil", func(t *testing.T) {
		if got := parseContentArray("plain text"); got != nil {
			t.Errorf("expected nil for string input, got %v", got)
		}
	})

	t.Run("string array elements treated as text blocks", func(t *testing.T) {
		input := []any{"hello", "world"}
		got := parseContentArray(input)
		if got == nil {
			t.Fatal("expected non-nil for string array")
		}
		if len(got) != 2 {
			t.Fatalf("expected 2 blocks, got %d", len(got))
		}
		if got[0].blockType != "text" || got[0].text != "hello" {
			t.Errorf("block 0 = %+v", got[0])
		}
		if got[1].blockType != "text" || got[1].text != "world" {
			t.Errorf("block 1 = %+v", got[1])
		}
	})

	t.Run("map array with text type", func(t *testing.T) {
		input := []any{
			map[string]any{"type": "text", "text": "hello"},
		}
		got := parseContentArray(input)
		if got == nil {
			t.Fatal("expected non-nil")
		}
		if len(got) != 1 {
			t.Fatalf("expected 1 block, got %d", len(got))
		}
		if got[0].blockType != "text" || got[0].text != "hello" {
			t.Errorf("block 0 = %+v", got[0])
		}
	})

	t.Run("map array with tool_use type", func(t *testing.T) {
		input := []any{
			map[string]any{"type": "tool_use", "id": "tu1", "name": "Bash", "input": map[string]any{"command": "ls"}},
		}
		got := parseContentArray(input)
		if got == nil {
			t.Fatal("expected non-nil")
		}
		if len(got) != 1 {
			t.Fatalf("expected 1 block, got %d", len(got))
		}
		if got[0].blockType != "tool_use" {
			t.Errorf("expected tool_use type, got %q", got[0].blockType)
		}
		if got[0].toolUse == nil {
			t.Fatal("expected non-nil toolUse")
		}
		if got[0].toolUse.name != "Bash" {
			t.Errorf("tool name = %q, want Bash", got[0].toolUse.name)
		}
	})

	t.Run("map array with tool_result type", func(t *testing.T) {
		input := []any{
			map[string]any{"type": "tool_result", "tool_use_id": "tu1", "content": "ok", "is_error": false},
		}
		got := parseContentArray(input)
		if got == nil {
			t.Fatal("expected non-nil")
		}
		if got[0].blockType != "tool_result" {
			t.Errorf("expected tool_result type, got %q", got[0].blockType)
		}
		if got[0].toolRes == nil {
			t.Fatal("expected non-nil toolRes")
		}
		if got[0].toolRes.toolUseID != "tu1" {
			t.Errorf("tool_use_id = %q, want tu1", got[0].toolRes.toolUseID)
		}
	})

	t.Run("non-string elements skipped", func(t *testing.T) {
		input := []any{42, true, nil}
		got := parseContentArray(input)
		// No structured blocks and no text blocks => nil
		if got != nil {
			t.Errorf("expected nil for non-string non-map elements, got %v", got)
		}
	})

	t.Run("empty string elements skipped", func(t *testing.T) {
		input := []any{"   "}
		got := parseContentArray(input)
		if got != nil {
			t.Errorf("expected nil for whitespace-only strings, got %v", got)
		}
	})

	t.Run("unknown block type extracts text via fallback", func(t *testing.T) {
		input := []any{
			map[string]any{"type": "unknown_type", "text": "fallback text"},
		}
		got := parseContentArray(input)
		if got == nil {
			t.Fatal("expected non-nil for unknown block with text")
		}
		if got[0].blockType != "text" || got[0].text != "fallback text" {
			t.Errorf("block 0 = %+v", got[0])
		}
	})

	t.Run("mixed text and structured blocks", func(t *testing.T) {
		input := []any{
			map[string]any{"type": "text", "text": "I'll check."},
			map[string]any{"type": "tool_use", "id": "tu1", "name": "Read"},
		}
		got := parseContentArray(input)
		if got == nil {
			t.Fatal("expected non-nil")
		}
		if len(got) != 2 {
			t.Fatalf("expected 2 blocks, got %d", len(got))
		}
		if got[0].blockType != "text" {
			t.Errorf("expected text block, got %q", got[0].blockType)
		}
		if got[1].blockType != "tool_use" {
			t.Errorf("expected tool_use block, got %q", got[1].blockType)
		}
	})
}

// ---------------------------------------------------------------------------
// serializeToolInput
// ---------------------------------------------------------------------------

func TestSerializeToolInput(t *testing.T) {
	t.Run("nil input returns empty", func(t *testing.T) {
		got := serializeToolInput("Bash", nil)
		if got != "" {
			t.Errorf("expected empty, got %q", got)
		}
	})

	t.Run("Bash extracts command", func(t *testing.T) {
		input := map[string]any{"command": "go test ./..."}
		got := serializeToolInput("Bash", input)
		if got != "go test ./..." {
			t.Errorf("got %q, want %q", got, "go test ./...")
		}
	})

	t.Run("bash lowercase extracts command", func(t *testing.T) {
		input := map[string]any{"command": "ls -la"}
		got := serializeToolInput("bash", input)
		if got != "ls -la" {
			t.Errorf("got %q, want %q", got, "ls -la")
		}
	})

	t.Run("Read extracts file_path", func(t *testing.T) {
		input := map[string]any{"file_path": "main.go"}
		got := serializeToolInput("Read", input)
		if got != "main.go" {
			t.Errorf("got %q, want %q", got, "main.go")
		}
	})

	t.Run("Read extracts path fallback", func(t *testing.T) {
		input := map[string]any{"path": "main.go"}
		got := serializeToolInput("Read", input)
		if got != "main.go" {
			t.Errorf("got %q, want %q", got, "main.go")
		}
	})

	t.Run("Edit extracts file_path", func(t *testing.T) {
		input := map[string]any{"file_path": "handler.go"}
		got := serializeToolInput("Edit", input)
		if got != "handler.go" {
			t.Errorf("got %q, want %q", got, "handler.go")
		}
	})

	t.Run("write lowercase extracts path", func(t *testing.T) {
		input := map[string]any{"path": "output.txt"}
		got := serializeToolInput("write", input)
		if got != "output.txt" {
			t.Errorf("got %q, want %q", got, "output.txt")
		}
	})

	t.Run("Grep extracts pattern", func(t *testing.T) {
		input := map[string]any{"pattern": "TODO"}
		got := serializeToolInput("Grep", input)
		if got != "TODO" {
			t.Errorf("got %q, want %q", got, "TODO")
		}
	})

	t.Run("Glob extracts pattern", func(t *testing.T) {
		input := map[string]any{"pattern": "**/*.go"}
		got := serializeToolInput("Glob", input)
		if got != "**/*.go" {
			t.Errorf("got %q, want %q", got, "**/*.go")
		}
	})

	t.Run("unknown tool falls back to JSON", func(t *testing.T) {
		input := map[string]any{"foo": "bar", "count": 3}
		got := serializeToolInput("CustomTool", input)
		if got == "" {
			t.Error("expected non-empty JSON fallback")
		}
		if !strings.Contains(got, "foo") || !strings.Contains(got, "bar") {
			t.Errorf("expected JSON containing foo/bar, got %q", got)
		}
	})

	t.Run("long input truncated", func(t *testing.T) {
		longVal := strings.Repeat("x", 300)
		input := map[string]any{"data": longVal}
		got := serializeToolInput("CustomTool", input)
		if len(got) <= maxToolInputChars+10 {
			// The "..." suffix is 3 chars, so total should be maxToolInputChars+3
		}
		if !strings.HasSuffix(got, "...") {
			t.Errorf("expected truncation suffix, got %q", got)
		}
	})

	t.Run("Bash without command key falls back to JSON", func(t *testing.T) {
		input := map[string]any{"other": "value"}
		got := serializeToolInput("Bash", input)
		if got == "" {
			t.Error("expected non-empty JSON fallback")
		}
	})
}

// ---------------------------------------------------------------------------
// unixTimestamp (threshold boundaries)
// ---------------------------------------------------------------------------

func TestUnixTimestampThresholds(t *testing.T) {
	tests := []struct {
		name  string
		input int64
		want  string
	}{
		{"seconds", 1704067200, "2024-01-01T00:00:00Z"},
		{"milliseconds", 1704067200000, "2024-01-01T00:00:00Z"},
		{"microseconds", 1704067200000000, "2024-01-01T00:00:00Z"},
		{"nanoseconds", 1704067200000000000, "2024-01-01T00:00:00Z"},
		{"negative seconds", -86400, "1969-12-31T00:00:00Z"},
		{"zero", 0, "1970-01-01T00:00:00Z"},
		{"one", 1, "1970-01-01T00:00:01Z"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := unixTimestamp(tt.input)
			parsed, _ := time.Parse(time.RFC3339, tt.want)
			if !got.Equal(parsed) {
				t.Errorf("unixTimestamp(%d) = %v, want %v", tt.input, got, parsed)
			}
		})
	}
}

// ---------------------------------------------------------------------------
// parseTimestamp: json.Number branch coverage
// ---------------------------------------------------------------------------

func TestParseTimestamp_JSONNumberInt64(t *testing.T) {
	got, ok := parseTimestamp(json.Number("1704067200"))
	if !ok {
		t.Fatal("expected ok for json.Number int64")
	}
	want := time.Date(2024, 1, 1, 0, 0, 0, 0, time.UTC)
	if !got.Equal(want) {
		t.Errorf("got %v, want %v", got, want)
	}
}

func TestParseTimestamp_JSONNumberFloat64(t *testing.T) {
	got, ok := parseTimestamp(json.Number("1704067200.5"))
	if !ok {
		t.Fatal("expected ok for json.Number float64")
	}
	want := time.Date(2024, 1, 1, 0, 0, 0, 0, time.UTC)
	if !got.Equal(want) {
		t.Errorf("got %v, want %v", got, want)
	}
}

func TestParseTimestamp_JSONNumberUnparseable(t *testing.T) {
	_, ok := parseTimestamp(json.Number("not-a-number"))
	if ok {
		t.Error("expected !ok for unparseable json.Number")
	}
}

func TestParseTimestamp_JSONNumberNanoseconds(t *testing.T) {
	got, ok := parseTimestamp(json.Number("1704067200000000000"))
	if !ok {
		t.Fatal("expected ok for json.Number nanoseconds")
	}
	want := time.Date(2024, 1, 1, 0, 0, 0, 0, time.UTC)
	if !got.Equal(want) {
		t.Errorf("got %v, want %v", got, want)
	}
}

func TestParseTimestamp_ZeroValues(t *testing.T) {
	tests := []struct {
		name  string
		value any
	}{
		{"int64(0)", int64(0)},
		{"int(0)", int(0)},
		{"float64(0)", float64(0)},
		{"uint64(0)", uint64(0)},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, ok := parseTimestamp(tt.value)
			if !ok {
				t.Fatalf("expected ok for %v", tt.value)
			}
			want := time.Date(1970, 1, 1, 0, 0, 0, 0, time.UTC)
			if !got.Equal(want) {
				t.Errorf("got %v, want %v", got, want)
			}
		})
	}
}

// ---------------------------------------------------------------------------
// roleFromRecord: sender / author map branches
// ---------------------------------------------------------------------------

func TestRoleFromRecordSenderKey(t *testing.T) {
	record := map[string]any{"sender": "human"}
	got := roleFromRecord(record)
	if got != "user" {
		t.Errorf("roleFromRecord(sender=human) = %q, want user", got)
	}
}

func TestRoleFromRecordAuthorKey(t *testing.T) {
	record := map[string]any{"author": "copilot"}
	got := roleFromRecord(record)
	if got != "assistant" {
		t.Errorf("roleFromRecord(author=copilot) = %q, want assistant", got)
	}
}

func TestRoleFromRecordAuthorMapWithRole(t *testing.T) {
	record := map[string]any{
		"author": map[string]any{"role": "user"},
	}
	got := roleFromRecord(record)
	if got != "user" {
		t.Errorf("roleFromRecord(author map with role=user) = %q, want user", got)
	}
}

func TestRoleFromRecordAuthorMapWithType(t *testing.T) {
	record := map[string]any{
		"author": map[string]any{"type": "assistant"},
	}
	got := roleFromRecord(record)
	if got != "assistant" {
		t.Errorf("roleFromRecord(author map with type=assistant) = %q, want assistant", got)
	}
}

func TestRoleFromRecordAuthorMapWithKind(t *testing.T) {
	record := map[string]any{
		"author": map[string]any{"kind": "model"},
	}
	got := roleFromRecord(record)
	if got != "assistant" {
		t.Errorf("roleFromRecord(author map with kind=model) = %q, want assistant", got)
	}
}

func TestRoleFromRecordEmptyReturnsEmpty(t *testing.T) {
	record := map[string]any{"irrelevant": 42}
	got := roleFromRecord(record)
	if got != "" {
		t.Errorf("roleFromRecord(irrelevant) = %q, want empty", got)
	}
}

// ---------------------------------------------------------------------------
// rawRole: map branch
// ---------------------------------------------------------------------------

func TestRawRoleMapWithNestedRole(t *testing.T) {
	input := map[string]any{"role": "assistant"}
	got := rawRole(input)
	if got != "assistant" {
		t.Errorf("rawRole(map[role:assistant]) = %q, want assistant", got)
	}
}

func TestRawRoleMapWithNestedType(t *testing.T) {
	input := map[string]any{"type": "user"}
	got := rawRole(input)
	if got != "user" {
		t.Errorf("rawRole(map[type:user]) = %q, want user", got)
	}
}

func TestRawRoleMapEmpty(t *testing.T) {
	input := map[string]any{}
	got := rawRole(input)
	if got != "" {
		t.Errorf("rawRole(empty map) = %q, want empty", got)
	}
}

func TestRawRoleNonStringNonMap(t *testing.T) {
	got := rawRole(42)
	if got != "" {
		t.Errorf("rawRole(42) = %q, want empty", got)
	}
}

// ---------------------------------------------------------------------------
// contentFromRecord: text / body / prompt branches
// ---------------------------------------------------------------------------

func TestContentFromRecordTextKey(t *testing.T) {
	record := map[string]any{"text": "hello from text key"}
	got := contentFromRecord(record)
	if got != "hello from text key" {
		t.Errorf("contentFromRecord(text) = %q, want %q", got, "hello from text key")
	}
}

func TestContentFromRecordBodyKey(t *testing.T) {
	record := map[string]any{"body": "hello from body key"}
	got := contentFromRecord(record)
	if got != "hello from body key" {
		t.Errorf("contentFromRecord(body) = %q, want %q", got, "hello from body key")
	}
}

func TestContentFromRecordPromptKey(t *testing.T) {
	record := map[string]any{"prompt": "hello from prompt key"}
	got := contentFromRecord(record)
	if got != "hello from prompt key" {
		t.Errorf("contentFromRecord(prompt) = %q, want %q", got, "hello from prompt key")
	}
}

func TestContentFromRecordResponseKey(t *testing.T) {
	record := map[string]any{"response": "hello from response key"}
	got := contentFromRecord(record)
	if got != "hello from response key" {
		t.Errorf("contentFromRecord(response) = %q, want %q", got, "hello from response key")
	}
}

func TestContentFromRecordEmptyReturnsEmpty(t *testing.T) {
	record := map[string]any{"irrelevant": 42}
	got := contentFromRecord(record)
	if got != "" {
		t.Errorf("contentFromRecord(irrelevant) = %q, want empty", got)
	}
}

// ---------------------------------------------------------------------------
// messageFromMap: timestamp fallback from root
// ---------------------------------------------------------------------------

func TestMessageFromMapTimestampFallbackFromRoot(t *testing.T) {
	// record has no timestamp; root does
	record := map[string]any{
		"role":    "user",
		"content": "hello",
	}
	root := map[string]any{
		"role":      "user",
		"content":   "hello",
		"timestamp": "2024-06-15T10:00:00Z",
	}
	msg, ok := messageFromMap(record, root)
	if !ok {
		t.Fatal("messageFromMap returned !ok")
	}
	expected := time.Date(2024, 6, 15, 10, 0, 0, 0, time.UTC)
	if !msg.Timestamp.Equal(expected) {
		t.Errorf("timestamp = %v, want %v", msg.Timestamp, expected)
	}
}

// ---------------------------------------------------------------------------
// nestedMessageCandidates
// ---------------------------------------------------------------------------

func TestNestedMessageCandidatesIncludesAllKeys(t *testing.T) {
	record := map[string]any{
		"message":  "m1",
		"event":    "e1",
		"data":     "d1",
		"payload":  "p1",
		"request":  "r1",
		"response": "r2",
		"messages": []any{"a", "b"},
	}
	candidates := nestedMessageCandidates(record)
	// 6 individual keys + 2 from messages array = 8
	if len(candidates) != 8 {
		t.Errorf("expected 8 candidates, got %d", len(candidates))
	}
}

// ---------------------------------------------------------------------------
// copilotSessionMessageFromRecord edge cases
// ---------------------------------------------------------------------------

func TestCopilotSessionMessageFromRecordNoType(t *testing.T) {
	record := map[string]any{"data": map[string]any{"content": "hi"}}
	_, ok := copilotSessionMessageFromRecord(record)
	if ok {
		t.Error("expected !ok for record without type")
	}
}

func TestCopilotSessionMessageFromRecordUnknownType(t *testing.T) {
	record := map[string]any{
		"type": "session.end",
		"data": map[string]any{"content": "bye"},
	}
	_, ok := copilotSessionMessageFromRecord(record)
	if ok {
		t.Error("expected !ok for unknown type")
	}
}

func TestCopilotSessionMessageFromRecordNoData(t *testing.T) {
	record := map[string]any{"type": "user.message"}
	_, ok := copilotSessionMessageFromRecord(record)
	if ok {
		t.Error("expected !ok for record without data")
	}
}

func TestCopilotSessionMessageFromRecordEmptyContent(t *testing.T) {
	record := map[string]any{
		"type": "user.message",
		"data": map[string]any{"content": ""},
	}
	_, ok := copilotSessionMessageFromRecord(record)
	if ok {
		t.Error("expected !ok for empty content")
	}
}

// ---------------------------------------------------------------------------
// parseJSONLRecordBytes: copilot session dispatch
// ---------------------------------------------------------------------------

func TestParseJSONLRecordBytesCopilotUserMessage(t *testing.T) {
	raw := []byte(`{"type":"user.message","data":{"content":"test input"}}`)
	msg, err, ok := parseJSONLRecordBytes(raw)
	if err != nil {
		t.Fatalf("parseJSONLRecordBytes returned error: %v", err)
	}
	if !ok {
		t.Fatal("expected ok")
	}
	if msg.Role != "user" || msg.Content != "test input" {
		t.Errorf("got role=%q content=%q", msg.Role, msg.Content)
	}
}

func TestParseJSONLRecordBytesCopilotAssistantMessage(t *testing.T) {
	raw := []byte(`{"type":"assistant.message","data":{"content":"test reply"}}`)
	msg, err, ok := parseJSONLRecordBytes(raw)
	if err != nil {
		t.Fatalf("parseJSONLRecordBytes returned error: %v", err)
	}
	if !ok {
		t.Fatal("expected ok")
	}
	if msg.Role != "assistant" || msg.Content != "test reply" {
		t.Errorf("got role=%q content=%q", msg.Role, msg.Content)
	}
}

// ---------------------------------------------------------------------------
// ReadJSONL: scanner error path (excessively long line)
// ---------------------------------------------------------------------------

func TestReadJSONLReturnsErrorForExcessivelyLongLine(t *testing.T) {
	filePath := filepath.Join(t.TempDir(), "toolong.jsonl")
	// Write a line that exceeds maxScannerBufferSize (8MB).
	hugeContent := strings.Repeat("a", 9*1024*1024)
	line := fmt.Sprintf(`{"role":"user","content":%q}`, hugeContent)
	if err := os.WriteFile(filePath, []byte(line+"\n"), 0o644); err != nil {
		t.Fatalf("WriteFile: %v", err)
	}
	_, err := ReadJSONL(filePath)
	if err == nil {
		t.Fatal("expected error for line exceeding scanner buffer")
	}
}

// ---------------------------------------------------------------------------
// ReadJSONLWithOptions: copilot sanitizer integration
// ---------------------------------------------------------------------------

func TestReadJSONLWithOptionsSanitizesCopilotDeduplication(t *testing.T) {
	filePath := filepath.Join(t.TempDir(), "copilot-dedup.jsonl")
	contents := strings.Join([]string{
		`{"type":"user.message","data":{"content":"Fix the bug."}}`,
		`{"type":"user.message","data":{"content":"Fix the bug."}}`,
		`{"type":"assistant.message","data":{"content":"I'll look into it."}}`,
	}, "\n")
	if err := os.WriteFile(filePath, []byte(contents), 0o644); err != nil {
		t.Fatalf("WriteFile: %v", err)
	}
	messages, err := ReadJSONLWithOptions(filePath, JSONLReadOptions{Sanitizer: SanitizeCopilotSessionMessages})
	if err != nil {
		t.Fatalf("ReadJSONLWithOptions: %v", err)
	}
	if len(messages) != 2 {
		t.Fatalf("expected 2 after dedup, got %d", len(messages))
	}
}

func TestReadJSONLWithOptionsResultTruncatesAtBudget(t *testing.T) {
	filePath := filepath.Join(t.TempDir(), "budget.jsonl")
	contents := strings.Join([]string{
		`{"role":"user","content":"12345"}`,
		`{"role":"assistant","content":"abcdef"}`,
		`{"role":"user","content":"must not be read"}`,
	}, "\n")
	if err := os.WriteFile(filePath, []byte(contents), 0o644); err != nil {
		t.Fatalf("WriteFile: %v", err)
	}

	result, err := ReadJSONLWithOptionsResult(filePath, JSONLReadOptions{
		Budget: ReadBudget{MaxBytes: len("user: \n") + len("12345") + len("assistant: \n") + 3},
	})
	if err != nil {
		t.Fatalf("ReadJSONLWithOptionsResult: %v", err)
	}
	if !result.Truncated {
		t.Fatal("expected truncated result")
	}
	if len(result.Messages) != 2 {
		t.Fatalf("len(Messages) = %d, want 2", len(result.Messages))
	}
	if got := result.Messages[1].Content; got != "abc" {
		t.Fatalf("truncated content = %q, want abc", got)
	}
	if strings.Contains(result.Messages[len(result.Messages)-1].Content, "must not") {
		t.Fatal("reader kept content after budget should have stopped scanning")
	}
}
