package readers

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func TestReadJSONLParsesMessagesAndSkipsMalformedLines(t *testing.T) {
	filePath := filepath.Join(t.TempDir(), "session.jsonl")
	contents := strings.Join([]string{
		`{"role":"user","content":"hello","timestamp":"2024-01-01T00:00:00Z"}`,
		`{this is not valid json}`,
		`{"message":{"author":{"role":"assistant"},"content":{"parts":["hi there"]},"createdAt":1704067800}}`,
		`{"event":"heartbeat"}`,
	}, "\n")

	if err := os.WriteFile(filePath, []byte(contents), 0o644); err != nil {
		t.Fatalf("WriteFile returned error: %v", err)
	}

	messages, err := ReadJSONL(filePath)
	if err != nil {
		t.Fatalf("ReadJSONL returned error: %v", err)
	}
	if len(messages) != 2 {
		t.Fatalf("expected 2 parsed messages, got %d", len(messages))
	}

	if got := messages[0].Role; got != "user" {
		t.Fatalf("first message role = %q, want user", got)
	}
	if got := messages[0].Content; got != "hello" {
		t.Fatalf("first message content = %q, want hello", got)
	}

	expectedSecondTime := time.Unix(1704067800, 0).UTC()
	if got := messages[1].Role; got != "assistant" {
		t.Fatalf("second message role = %q, want assistant", got)
	}
	if got := messages[1].Content; got != "hi there" {
		t.Fatalf("second message content = %q, want hi there", got)
	}
	if !messages[1].Timestamp.Equal(expectedSecondTime) {
		t.Fatalf("second message timestamp = %s, want %s", messages[1].Timestamp, expectedSecondTime)
	}
}

func TestReadJSONLSupportsLargeLines(t *testing.T) {
	filePath := filepath.Join(t.TempDir(), "large-session.jsonl")
	largeContent := strings.Repeat("a", 70*1024)
	line := fmt.Sprintf(`{"role":"user","content":%q}`, largeContent)

	if err := os.WriteFile(filePath, []byte(line+"\n"), 0o644); err != nil {
		t.Fatalf("WriteFile returned error: %v", err)
	}

	messages, err := ReadJSONL(filePath)
	if err != nil {
		t.Fatalf("ReadJSONL returned error: %v", err)
	}
	if len(messages) != 1 {
		t.Fatalf("expected 1 parsed message, got %d", len(messages))
	}
	if got := len(messages[0].Content); got != len(largeContent) {
		t.Fatalf("parsed content length = %d, want %d", got, len(largeContent))
	}
}

func TestReadJSONLReturnsOpenError(t *testing.T) {
	_, err := ReadJSONL(filepath.Join(t.TempDir(), "missing.jsonl"))
	if err == nil {
		t.Fatalf("ReadJSONL expected error for missing file")
	}
}

func TestReadJSONLParsesClaudeCodeSessionRecords(t *testing.T) {
	filePath := filepath.Join(t.TempDir(), "claude-session.jsonl")
	contents := strings.Join([]string{
		`{"type":"queue-operation","sessionId":"abc","operation":"enqueue","timestamp":"2026-05-08T12:00:00Z"}`,
		`{"type":"user","message":{"role":"user","content":"Help me debug this"},"timestamp":"2026-05-08T12:00:01Z"}`,
		`{"type":"assistant","message":{"role":"assistant","content":[{"type":"text","text":"Sure, share the error."}]},"timestamp":"2026-05-08T12:00:02Z"}`,
	}, "\n")

	if err := os.WriteFile(filePath, []byte(contents), 0o644); err != nil {
		t.Fatalf("WriteFile returned error: %v", err)
	}

	messages, err := ReadJSONL(filePath)
	if err != nil {
		t.Fatalf("ReadJSONL returned error: %v", err)
	}
	if len(messages) != 2 {
		t.Fatalf("expected 2 parsed messages, got %d", len(messages))
	}

	if got := messages[0].Role; got != "user" {
		t.Fatalf("first message role = %q, want user", got)
	}
	if got := messages[0].Content; got != "Help me debug this" {
		t.Fatalf("first message content = %q, want expected Claude user content", got)
	}
	if got := messages[1].Role; got != "assistant" {
		t.Fatalf("second message role = %q, want assistant", got)
	}
	if got := messages[1].Content; got != "Sure, share the error." {
		t.Fatalf("second message content = %q, want expected Claude assistant content", got)
	}
}

func TestReadJSONLWithOptionsSanitizesClaudeRecords(t *testing.T) {
	filePath := filepath.Join(t.TempDir(), "claude-session-sanitized.jsonl")
	contents := strings.Join([]string{
		`{"type":"user","message":{"role":"user","content":"<local-command-caveat>generated by the user while running local commands</local-command-caveat>"},"timestamp":"2026-05-08T12:00:00Z"}`,
		`{"type":"user","message":{"role":"user","content":"Need help\nwith tests"},"timestamp":"2026-05-08T12:00:01Z"}`,
		`{"type":"user","message":{"role":"user","content":"Need   help with tests"},"timestamp":"2026-05-08T12:00:02Z"}`,
		`{"type":"user","message":{"role":"user","content":"Async agent launched successfully. agentId: a1 output_file: C:\\temp\\x"},"timestamp":"2026-05-08T12:00:03Z"}`,
		`{"type":"assistant","message":{"role":"assistant","content":"Sure, share go test output."},"timestamp":"2026-05-08T12:00:04Z"}`,
	}, "\n")

	if err := os.WriteFile(filePath, []byte(contents), 0o644); err != nil {
		t.Fatalf("WriteFile returned error: %v", err)
	}

	messages, err := ReadJSONLWithOptions(filePath, JSONLReadOptions{SanitizeClaude: true})
	if err != nil {
		t.Fatalf("ReadJSONLWithOptions returned error: %v", err)
	}
	if len(messages) != 2 {
		t.Fatalf("expected 2 sanitized Claude messages, got %d", len(messages))
	}
	if got := messages[0].Content; got != "Need help with tests" {
		t.Fatalf("first message content = %q, want sanitized content", got)
	}
	if got := messages[1].Content; got != "Sure, share go test output." {
		t.Fatalf("second message content = %q, want assistant content", got)
	}
}

func TestReadJSONLWithOptionsDefaultDoesNotSanitize(t *testing.T) {
	filePath := filepath.Join(t.TempDir(), "claude-session-raw.jsonl")
	contents := strings.Join([]string{
		`{"type":"user","message":{"role":"user","content":"<local-command-stdout>Set model</local-command-stdout>"},"timestamp":"2026-05-08T12:00:00Z"}`,
		`{"type":"user","message":{"role":"user","content":"Need help\nwith tests"},"timestamp":"2026-05-08T12:00:01Z"}`,
		`{"type":"user","message":{"role":"user","content":"Need   help with tests"},"timestamp":"2026-05-08T12:00:02Z"}`,
		`{"type":"assistant","message":{"role":"assistant","content":"Sure, share go test output."},"timestamp":"2026-05-08T12:00:03Z"}`,
	}, "\n")

	if err := os.WriteFile(filePath, []byte(contents), 0o644); err != nil {
		t.Fatalf("WriteFile returned error: %v", err)
	}

	messages, err := ReadJSONLWithOptions(filePath, JSONLReadOptions{})
	if err != nil {
		t.Fatalf("ReadJSONLWithOptions returned error: %v", err)
	}
	if len(messages) != 4 {
		t.Fatalf("expected 4 unsanitized Claude messages, got %d", len(messages))
	}
	if got := messages[0].Content; !strings.Contains(got, "<local-command-stdout>") {
		t.Fatalf("first message content = %q, want unsanitized wrapper content", got)
	}
}

func TestReadJSONLWithOptionsSanitizesNoisyClaudePayloadAndKeepsSignal(t *testing.T) {
	filePath := filepath.Join(t.TempDir(), "claude-noisy-session.jsonl")
	contents := strings.Join([]string{
		`{"type":"user","message":{"role":"user","content":"<meta>trace metadata</meta>"},"timestamp":"2026-05-08T12:00:00Z"}`,
		`{"type":"assistant","message":{"role":"assistant","content":"tool_result: {\"ok\":true}"},"timestamp":"2026-05-08T12:00:01Z"}`,
		`{"type":"user","message":{"role":"user","content":"Async agent launched successfully. agentId: a1 output_file: C:\\temp\\a"},"timestamp":"2026-05-08T12:00:02Z"}`,
		`{"type":"user","message":{"role":"user","content":"  Please investigate flaky daemon cycle behavior.  "},"timestamp":"2026-05-08T12:00:03Z"}`,
		`{"type":"assistant","message":{"role":"assistant","content":[{"type":"text","text":"I will inspect runtime and discovery isolation tests."}]},"timestamp":"2026-05-08T12:00:04Z"}`,
		`{"type":"user","message":{"role":"user","content":"Need help\nwith project A/B isolation"},"timestamp":"2026-05-08T12:00:05Z"}`,
	}, "\n")

	if err := os.WriteFile(filePath, []byte(contents), 0o644); err != nil {
		t.Fatalf("WriteFile returned error: %v", err)
	}

	messages, err := ReadJSONLWithOptions(filePath, JSONLReadOptions{SanitizeClaude: true})
	if err != nil {
		t.Fatalf("ReadJSONLWithOptions returned error: %v", err)
	}
	if len(messages) != 4 {
		t.Fatalf("expected 4 sanitized Claude signal messages, got %d", len(messages))
	}

	if got := messages[0].Content; got != "tool_result: {\"ok\":true}" {
		t.Fatalf("first message content = %q, want kept tool result reference", got)
	}
	if got := messages[1].Content; got != "Please investigate flaky daemon cycle behavior." {
		t.Fatalf("second message content = %q, want kept user signal", got)
	}
	if got := messages[2].Content; got != "I will inspect runtime and discovery isolation tests." {
		t.Fatalf("third message content = %q, want kept assistant signal", got)
	}
	if got := messages[3].Content; got != "Need help with project A/B isolation" {
		t.Fatalf("fourth message content = %q, want normalized user signal", got)
	}

	joined := strings.ToLower(messages[0].Content + " " + messages[1].Content + " " + messages[2].Content + " " + messages[3].Content)
	for _, unwanted := range []string{"<meta>", "async agent launched successfully", "output_file:"} {
		if strings.Contains(joined, unwanted) {
			t.Fatalf("sanitized messages should not include %q: %q", unwanted, joined)
		}
	}
}

func TestReadJSONLParsesCodexResponseItemPayloadMessages(t *testing.T) {
	filePath := filepath.Join(t.TempDir(), "codex-session.jsonl")
	contents := strings.Join([]string{
		`{"type":"session_meta","payload":{"cwd":"C:\\repo"}}`,
		`{"type":"response_item","payload":{"role":"user","content":"Please inspect daemon isolation."},"timestamp":"2026-05-08T12:00:01Z"}`,
		`{"type":"response_item","payload":{"role":"assistant","content":[{"type":"output_text","text":"I found a state merge issue."}]},"timestamp":"2026-05-08T12:00:02Z"}`,
	}, "\n")

	if err := os.WriteFile(filePath, []byte(contents), 0o644); err != nil {
		t.Fatalf("WriteFile returned error: %v", err)
	}

	messages, err := ReadJSONL(filePath)
	if err != nil {
		t.Fatalf("ReadJSONL returned error: %v", err)
	}
	if len(messages) != 2 {
		t.Fatalf("expected 2 parsed Codex messages, got %d", len(messages))
	}

	if got := messages[0].Role; got != "user" {
		t.Fatalf("first message role = %q, want user", got)
	}
	if got := messages[0].Content; got != "Please inspect daemon isolation." {
		t.Fatalf("first message content = %q, want Codex user content", got)
	}
	if got := messages[1].Role; got != "assistant" {
		t.Fatalf("second message role = %q, want assistant", got)
	}
	if got := messages[1].Content; got != "I found a state merge issue." {
		t.Fatalf("second message content = %q, want Codex assistant content", got)
	}
}

func TestReadJSONLParsesCopilotSessionMessagesFromTypedEvents(t *testing.T) {
	filePath := filepath.Join(t.TempDir(), "copilot-session.jsonl")
	contents := strings.Join([]string{
		`{"type":"session.start","data":{"id":"s1"}}`,
		`{"type":"user.message","data":{"content":"How should I fix the daemon?"},"timestamp":"2026-05-08T12:00:01Z"}`,
		`{"type":"assistant.message","data":{"content":"Start by checking runtime routing."},"timestamp":"2026-05-08T12:00:02Z"}`,
		`{"type":"tool.execution_result","data":{"content":"large tool output"}}`,
	}, "\n")

	if err := os.WriteFile(filePath, []byte(contents), 0o644); err != nil {
		t.Fatalf("WriteFile returned error: %v", err)
	}

	messages, err := ReadJSONL(filePath)
	if err != nil {
		t.Fatalf("ReadJSONL returned error: %v", err)
	}
	if len(messages) != 2 {
		t.Fatalf("expected 2 parsed Copilot messages, got %d", len(messages))
	}
	if got := messages[0].Role; got != "user" {
		t.Fatalf("first message role = %q, want user", got)
	}
	if got := messages[0].Content; got != "How should I fix the daemon?" {
		t.Fatalf("first message content = %q, want user content", got)
	}
	if got := messages[1].Role; got != "assistant" {
		t.Fatalf("second message role = %q, want assistant", got)
	}
	if got := messages[1].Content; got != "Start by checking runtime routing." {
		t.Fatalf("second message content = %q, want assistant content", got)
	}
}

func TestReadJSONLWithOptionsSanitizesCopilotSessionNoise(t *testing.T) {
	filePath := filepath.Join(t.TempDir(), "copilot-session-sanitized.jsonl")
	contents := strings.Join([]string{
		`{"type":"session.info","data":{"content":"metadata"}}`,
		`{"type":"assistant.message","data":{"toolRequests":[{"id":"tool-1"}]}}`,
		`{"type":"user.message","data":{"content":"Need help\nwith VS Code chat parsing."}}`,
		`{"type":"user.message","data":{"content":"Need   help with VS Code chat parsing."}}`,
		`{"type":"assistant.message","data":{"content":"Read requests and response markdown only."}}`,
		`{"type":"tool.execution_start","data":{"content":"run command"}}`,
	}, "\n")

	if err := os.WriteFile(filePath, []byte(contents), 0o644); err != nil {
		t.Fatalf("WriteFile returned error: %v", err)
	}

	messages, err := ReadJSONLWithOptions(filePath, JSONLReadOptions{SanitizeCopilotSession: true})
	if err != nil {
		t.Fatalf("ReadJSONLWithOptions returned error: %v", err)
	}
	if len(messages) != 2 {
		t.Fatalf("expected 2 sanitized Copilot messages, got %d", len(messages))
	}
	if got := messages[0].Content; got != "Need help with VS Code chat parsing." {
		t.Fatalf("first message content = %q, want normalized user message", got)
	}
	if got := messages[1].Content; got != "Read requests and response markdown only." {
		t.Fatalf("second message content = %q, want assistant response", got)
	}
}

func TestReadJSONLIgnoresCodexResponseItemsWithoutUserAssistantRole(t *testing.T) {
	filePath := filepath.Join(t.TempDir(), "codex-session-ignore-non-chat.jsonl")
	contents := strings.Join([]string{
		`{"type":"response_item","payload":{"role":"system","content":"internal state checkpoint"}}`,
		`{"type":"response_item","payload":{"role":"tool","content":"tool output"}}`,
		`{"type":"response_item","payload":{"role":"user","content":"Need help with retries"}}`,
		`{"type":"response_item","payload":{"role":"assistant","content":"Add bounded backoff and tests."}}`,
	}, "\n")

	if err := os.WriteFile(filePath, []byte(contents), 0o644); err != nil {
		t.Fatalf("WriteFile returned error: %v", err)
	}

	messages, err := ReadJSONL(filePath)
	if err != nil {
		t.Fatalf("ReadJSONL returned error: %v", err)
	}
	if len(messages) != 2 {
		t.Fatalf("expected 2 parsed chat messages, got %d", len(messages))
	}

	if got := messages[0].Role; got != "user" {
		t.Fatalf("first message role = %q, want user", got)
	}
	if got := messages[1].Role; got != "assistant" {
		t.Fatalf("second message role = %q, want assistant", got)
	}
}

func TestReadJSONLWithOptionsSanitizesCodexBootstrapMessages(t *testing.T) {
	filePath := filepath.Join(t.TempDir(), "codex-session-sanitized.jsonl")
	contents := strings.Join([]string{
		`{"type":"session_meta","payload":{"cwd":"C:\\repo"}}`,
		`{"type":"response_item","payload":{"type":"message","role":"user","content":[{"type":"input_text","text":"# AGENTS.md instructions for C:\\repo\n\n<INSTRUCTIONS>\nPrioritize readability over cleverness.\n</INSTRUCTIONS>"}]},"timestamp":"2026-05-08T12:00:00Z"}`,
		`{"type":"response_item","payload":{"type":"message","role":"user","content":{"type":"input_text","text":"Please inspect flaky evaluation scoring."}},"timestamp":"2026-05-08T12:00:01Z"}`,
		`{"type":"response_item","payload":{"type":"message","role":"assistant","content":{"type":"output_text","text":"I found the scoring path and will keep the patch narrow."}},"timestamp":"2026-05-08T12:00:02Z"}`,
		`{"type":"response_item","payload":{"type":"message","role":"assistant","content":{"type":"output_text","text":"I found the scoring path and will keep the patch narrow."}},"timestamp":"2026-05-08T12:00:03Z"}`,
	}, "\n")

	if err := os.WriteFile(filePath, []byte(contents), 0o644); err != nil {
		t.Fatalf("WriteFile returned error: %v", err)
	}

	messages, err := ReadJSONLWithOptions(filePath, JSONLReadOptions{SanitizeCodex: true})
	if err != nil {
		t.Fatalf("ReadJSONLWithOptions returned error: %v", err)
	}
	if len(messages) != 2 {
		t.Fatalf("expected 2 sanitized Codex messages, got %d", len(messages))
	}
	if got := messages[0].Content; got != "Please inspect flaky evaluation scoring." {
		t.Fatalf("first message content = %q, want user request", got)
	}
	if got := messages[1].Content; got != "I found the scoring path and will keep the patch narrow." {
		t.Fatalf("second message content = %q, want assistant message", got)
	}
}
