package cmd

import (
	"bytes"
	"fmt"
	"path/filepath"
	"strings"
	"text/template"

	"dreamer/internal/analyzer"
	"dreamer/internal/config"
)

// configTemplate is the commented config.yaml emitted by `dreamer setup`.
// Lines marked {{.User…}} are interpolated from setupAnswers; everything
// else stays in place so operators can see every configurable knob and
// its documentation in the rendered file.
const configTemplate = `# dreamer global config (v1.5). See docs/spec.md for full schema.
#
# Generated by 'dreamer setup'. Re-running setup overwrites this file
# and drops comments — pin daemon-managed edits to the web UI's
# settings page (writes to ui-overrides.yaml) to preserve comments here.

# Provider used when --provider is not passed and no per-project config sets one.
# Options:
{{providerOptionsComment}}default_provider: {{.DefaultProvider}}

# Projects iterated by the daemon. Each entry: {name, path, since}.
#   name:  output subdir under <output_root>
#   path:  absolute project directory (symlinks resolved)
#   since: optional lookback window (e.g. "30m", "1h", "1d", "1w", "1mo", "lifetime")
{{- if .Projects}}
projects:
{{- range .Projects}}
  - name: {{.Name}}
    path: {{.Path}}
    since: {{.Since}}
{{- end}}
{{- else}}
projects: []
# Example:
#   - name: dreamer
#     path: /home/me/dev/dreamer
#     since: 7d
{{- end}}

daemon:
  # Sleep between daemon cycles. Integer seconds. Default: 3600 (1h).
  frequency_seconds: {{.FrequencySeconds}}
{{- if .OutputRoot}}
  output_root: {{.OutputRoot}}
{{- else}}
  # Output root override. Empty = <UserConfigDir>/dreamer.
  # output_root: ""
{{- end}}
  # How many analyses can run simultaneously. Default: 1.
  max_concurrent_jobs: 1
  # Per-job timeout (Go duration). Default: "8h".
  max_analysis_duration: "8h"
  # How long to keep completed job records. Default: "720h" (30 days).
  job_history_retention: "720h"

logging:
  # Verbosity. Options: error | warn | info | debug
  level: {{.LogLevel}}
  # Log file path. Empty = <output_root>/dreamer.log.
  file: ""

redaction:
  # Extra regex patterns appended to the built-in secret allow-list.
  # Each match becomes [REDACTED:custom]. See spec §6 for built-ins.
  patterns: []
  # Example:
  #   - "ACME_INTERNAL_[A-Z0-9]{32}"

providers:
  copilot-sdk:
    # GitHub Copilot SDK (native Go SDK). See spec §18.
    model: {{provModel "copilot-sdk" .UserProvider .UserModel}}   # "auto" = SDK auto-select. Override: gpt-5.3-codex | gpt-4.1 | gpt-5
    use_logged_in_user: true    # options: true | false. Use keychain auth. Mutually exclusive with cli_url.
    # copilot_home: ""          # override $COPILOT_HOME. Optional.
    # cli_url: ""               # connect to headless CLI server (e.g. "localhost:4321"). Disables use_logged_in_user.

  copilot-acp:
    # Copilot via Agent Client Protocol stdio transport (spec §4.4).
    # sandbox: auto              # Native sandbox is currently enforced on Windows only; other platforms keep agent policy checks.
    model: {{provModel "copilot-acp" .UserProvider .UserModel}}   # "auto" = agent auto-select (default)
    command: ["copilot", "--acp"]
    # env: {}                   # extra environment variables for the subprocess

  claude-cli:
    # Claude CLI via stream-json. Flags validated upstream; do not strip --output-format.
    # sandbox: auto              # Native sandbox is currently enforced on Windows only; other platforms keep CLI policy flags.
    model: {{provModel "claude-cli" .UserProvider .UserModel}}  # default. Override: claude-sonnet-4-5-20250929 | claude-opus-4-7-20250917
    command: ["claude", "-p", "--verbose", "--output-format=stream-json", "--permission-mode", "plan", "--bare", "--no-session-persistence"]
    # env: {}

  claude-acp:
    # sandbox: auto              # Native sandbox is currently enforced on Windows only; other platforms keep agent policy checks.
    model: {{provModel "claude-acp" .UserProvider .UserModel}}  # default
    command: ["npx", "-y", "@zed-industries/claude-code-acp"]
    # env: {}

  gemini-cli:
    # Gemini CLI via stream-json in headless mode.
    # sandbox: auto              # Native sandbox is currently enforced on Windows only; other platforms keep CLI policy flags.
    model: {{provModel "gemini-cli" .UserProvider .UserModel}}    # default. Fallback: gemini-2.5-flash
    command: ["gemini", "-p", "--output-format=stream-json", "--approval-mode=plan"]
    # env: {}

  gemini-acp:
    # sandbox: auto              # Native sandbox is currently enforced on Windows only; other platforms keep agent policy checks.
    model: {{provModel "gemini-acp" .UserProvider .UserModel}}    # default. Fallback: gemini-2.5-flash
    command: ["gemini", "--acp"]
    # env: {}

  kiro-acp:
    # Kiro CLI via ACP.
    # sandbox: auto              # Native sandbox is currently enforced on Windows only; other platforms keep agent policy checks.
    model: {{provModel "kiro-acp" .UserProvider .UserModel}}  # default
    command: ["kiro-cli", "acp"]
    # env: {}

  codex-cli:
    # OpenAI Codex CLI via 'codex exec --json' (spec v1.1).
    # Override command to add flags like --model, --image, or to point at a wrapper.
    # sandbox: auto              # Native sandbox is currently enforced on Windows only; other platforms keep CLI policy flags.
    model: {{provModel "codex-cli" .UserProvider .UserModel}}              # default. Override: gpt-5.4-mini-2026-03-17 | gpt-5
    command: ["codex", "exec", "--json", "--sandbox", "read-only"]
    # env: {}                   # extra environment for the subprocess

  codex-acp:
    # Codex via an ACP bridge supplied by the operator.
    # OpenAI's 'codex' binary does not ship a native ACP server yet, so the
    # 'command' field must point at a third-party bridge that speaks
    # JSON-RPC 2.0 over stdio.
    # sandbox: auto              # Native sandbox is currently enforced on Windows only; other platforms keep agent policy checks.
    model: {{provModel "codex-acp" .UserProvider .UserModel}}              # default
    command: ["codex-acp"]
    # env: {}

  openclaude-cli:
    # OpenClaude CLI via stream-json in headless mode.
    # Routed through Gitlawb Opengateway — free MiMo models, no auth needed
    # by the gateway itself. openclaude's openai-compatible transport still
    # checks for OPENAI_API_KEY when CLAUDE_CODE_USE_OPENAI=1, so we pass a
    # placeholder value the gateway ignores. OPENAI_BASE_URL + OPENAI_MODEL
    # mirror ~/.openclaude/.openclaude-profile.json so the subprocess does
    # not have to inherit them from an interactive shell.
    # sandbox: auto              # Native sandbox is currently enforced on Windows only; other platforms keep CLI policy flags.
    model: {{provModel "openclaude-cli" .UserProvider .UserModel}}
    command: ["openclaude", "-p", "--verbose", "--output-format=stream-json", "--permission-mode", "plan", "--bare", "--no-session-persistence"]
    env:
      OPENAI_BASE_URL: "https://opengateway.gitlawb.com/v1"
      OPENAI_MODEL: "mimo-v2.5-pro"
      OPENAI_API_KEY: "free-via-opengateway"
      CLAUDE_CODE_USE_OPENAI: "1"

# Analyzer settings.
# rule_timeout_seconds: global timeout for every provider call (phase-1 + phase-2).
#                       Applied to all rule packs; overrides per-pack defaults.
#                       Set higher for slow providers / large transcripts.
# rules:                per-category enable/disable overrides.
# Categories: lint-rule | test | ci-check | doc | config | refactor-boundary
analyzer:
  rule_timeout_seconds: {{.RuleTimeoutSeconds}}
{{- if or .Parallel .MaxChunkBytes}}
  execution:
    # Mode: sequential | parallel. Parallel requires ParallelCapable providers.
    mode: {{if .Parallel}}parallel{{else}}sequential{{end}}
{{- if and .Parallel (gt .MaxConcurrency 0)}}
    max_concurrency: {{.MaxConcurrency}}
{{- end}}
{{- if .MaxChunkBytes}}
  chunking:
    # Max bytes per chunk fed to a single provider session. Default: 480000.
    max_chunk_bytes: {{.MaxChunkBytes}}
{{- end}}
{{- end}}
  # rules:
  #   lint-rule:
  #     enabled: true
  #   refactor-boundary:
  #     enabled: false

# Embedded web UI [v1.5]. Loopback-only; v1.6 will introduce token auth
# for remote binds.
web:
  enabled: true        # Set false to disable the dashboard entirely.
  port: 7777           # 0 = ephemeral; the chosen port lands in <output_root>/web.port.
  host: 127.0.0.1      # Loopback-only. 0.0.0.0 fails validation.
  log_tail_kb: 256     # Max KB of dreamer.log served by /api/logs/tail.
`

// renderCommentedConfig substitutes the wizard's answers into the
// commented template and returns the rendered bytes ready to write.
func renderCommentedConfig(a setupAnswers) ([]byte, error) {
	tmplData := struct {
		DefaultProvider    string
		UserProvider       string
		UserModel          string
		FrequencySeconds   int
		OutputRoot         string
		LogLevel           string
		RuleTimeoutSeconds int
		Parallel           bool
		MaxConcurrency     int
		MaxChunkBytes      int
		Projects           []templateProject
	}{
		DefaultProvider:    valueOr(a.provider, "openclaude-cli"),
		UserProvider:       a.provider,
		UserModel:          a.model,
		FrequencySeconds:   intOr(a.frequency, 3600),
		OutputRoot:         a.outputRoot,
		LogLevel:           valueOr(a.logLevel, "info"),
		RuleTimeoutSeconds: intOr(a.ruleTimeout, 120),
		Parallel:           a.parallel,
		MaxConcurrency:     a.maxConcurrency,
		MaxChunkBytes:      a.maxChunkBytes,
	}
	if a.firstProject && a.projectPath != "" {
		name := a.projectName
		if name == "" {
			name = filepath.Base(a.projectPath)
		}
		since := a.projectSince
		if since == "" {
			since = "24h"
		}
		tmplData.Projects = []templateProject{{Name: name, Path: a.projectPath, Since: since}}
	}

	tmpl := template.New("config").Funcs(template.FuncMap{
		// provModel emits the user's chosen model for the block whose id
		// matches userProvider, and the documented default for every other
		// block. Keeps non-selected provider blocks at their canonical
		// defaults so the rendered file documents every option.
		"provModel": func(blockID, userProvider, userModel string) string {
			if blockID == userProvider && strings.TrimSpace(userModel) != "" {
				return userModel
			}
			if m := config.DefaultModelFor(blockID); m != "" {
				return m
			}
			return ""
		},
		// providerOptionsComment renders the "# Options:" block from the
		// analyzer registry so the documented provider list cannot drift
		// from the registered set. Three IDs per row, indented to align
		// under "# Options:".
		"providerOptionsComment": func() string {
			meta := analyzer.RegisteredProviderMeta()
			var builder strings.Builder
			const perRow = 3
			for i, m := range meta {
				if i%perRow == 0 {
					builder.WriteString("#   ")
				}
				builder.WriteString(string(m.ID))
				if i == len(meta)-1 {
					builder.WriteString("\n")
				} else if (i+1)%perRow == 0 {
					builder.WriteString("\n")
				} else {
					builder.WriteString(" | ")
				}
			}
			return builder.String()
		},
	})
	tmpl, err := tmpl.Parse(configTemplate)
	if err != nil {
		return nil, fmt.Errorf("parse config template: %w", err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, tmplData); err != nil {
		return nil, fmt.Errorf("execute config template: %w", err)
	}
	return buf.Bytes(), nil
}

type templateProject struct {
	Name  string
	Path  string
	Since string
}

func valueOr(v, fallback string) string {
	if strings.TrimSpace(v) == "" {
		return fallback
	}
	return v
}

func intOr(v, fallback int) int {
	if v <= 0 {
		return fallback
	}
	return v
}
